version: "3"
services:
  invidious_companion:
    build:
      context: .
      dockerfile: Dockerfile
    # image: quay.io/invidious/invidious-companion:latest
    ports:
      - 127.0.0.1:8282:8282
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    user: 10001:10001
    # cache for youtube library
    volumes:
      - /var/tmp/youtubei.js:/var/tmp/youtubei.js:rw
    security_opt:
      - no-new-privileges:true
